const assert = require('assert');
const renderer = require('../assets/js/recruitment-role-detail');
let innerHtmlWrites = 0;
let invalidReplaceChildCount = 0;
class ChildrenCollection { constructor(owner){this.owner=owner;} get length(){return this.owner._children.length;} item(i){return this.owner._children[i]||null;} [Symbol.iterator](){return this.owner._children[Symbol.iterator]();} forEach(fn){this.owner._children.forEach(fn);} map(fn){return this.owner._children.map(fn);} filter(fn){return this.owner._children.filter(fn);} }
class Element { constructor(t){this.tagName=t.toUpperCase();this._children=[];this.children=new ChildrenCollection(this);this.attributes={};this.className='';this._textContent='';} appendChild(c){assert(c instanceof Element, 'appendChild received a non-node value');this._children.push(c);return c;} replaceChildren(...c){c.forEach(child=>{if(!(child instanceof Element))invalidReplaceChildCount++;});this._children=c;} set href(v){this.attributes.href=v;} get href(){return this.attributes.href;} set innerHTML(v){innerHtmlWrites++;this._textContent=String(v);} set textContent(v){this._textContent=String(v);this._children=[];} get textContent(){return this._textContent+this._children.map(c=>c.textContent).join('');} setAttribute(n,v){this.attributes[n]=String(v);} getAttribute(n){return this.attributes[n]||null;} findByTag(t,f=[]){if(this.tagName===t.toUpperCase())f.push(this);this._children.forEach(c=>c.findByTag(t,f));return f;} }
class Document { constructor(lang,id){this.documentElement={lang};this.hero=new Element('div');this.body_=new Element('body');if(id!==undefined)this.body_.attributes['data-recruitment-role-id']=id;this.bodyEl=new Element('section');this.langLink=new Element('a');this.langLink.className='sv-lang';this.langLink.attributes.href=id+'_cn.html';} get body(){return this.body_;} createElement(t){return new Element(t);} querySelector(s){if(s==='[data-role-detail="hero"]')return this.hero;if(s==='[data-role-detail="body"]')return this.bodyEl;return null;} querySelectorAll(s){return s.includes('sv-lang')?[this.langLink]:[];} }
function role(status='published'){return {id:'legal-assistant',slug:'legal-assistant',status,contentReviewRequired:false,contentReviewNote:'secret',title:{en:'Legal Assistant','zh-CN':'法务专员'},location:{en:'Guangzhou, China','zh-CN':'中国广东省广州市'},department:{en:'Legal Department','zh-CN':'法务部门'},reportingLine:{en:'Legal Supervisor','zh-CN':'法务主管'},employmentType:{en:'Full-time','zh-CN':'全职'},targetStartDate:{en:'Immediate availability preferred','zh-CN':'尽快到岗'},roleOverview:{en:'Overview text.','zh-CN':'概述。'},responsibilities:{en:['Do legal work'],'zh-CN':['法务工作']},requiredQualifications:{en:['Law degree'],'zh-CN':['法学学历']},preferredQualifications:{en:['Fund certificate preferred'],'zh-CN':['基金从业优先']},recruitmentStatus:{en:'Open until filled','zh-CN':'招到为止'},datePosted:'2026-07-20',dateUpdated:'2026-07-20',displayOrder:1,emailApplicationCopy:{en:{heading:'How to apply',copy:'Please email your CV to hr@shorevest.com and include “Legal Assistant” and your full name in the subject line.',button:'Apply by email',subject:'Application - Legal Assistant - [Full Name]',body:'Full name:\n\nTelephone:\n\nCurrent location:\n\nLinkedIn:\n\nShort note:\n\nCV attached: Yes / No'},'zh-CN':{heading:'申请方式',copy:'请将个人简历发送至 hr@shorevest.com，并在邮件主题中注明“法务专员”及您的姓名。',button:'通过邮件申请',subject:'申请 - 法务专员 - [姓名]',body:'姓名：\n\n联系电话：\n\n目前所在地：\n\n领英：\n\n简短说明：\n\n已附简历：是 / 否'}}};}
function render(lang,id,roles,preview=false){let d=new Document(lang,id);let status=renderer.renderRoleDetail(d,{schemaVersion:'1.0',emailApplication:{enabled:true,address:'hr@shorevest.com'},roles},{roleId:id,preview});return {d,status,text:()=>d.hero.textContent+d.bodyEl.textContent};}
let r=render('en','legal-assistant',[role()]); assert.strictEqual(r.status,'published'); assert.match(r.text(),/Legal Assistant/); assert.match(r.text(),/Legal Supervisor/); assert.match(r.text(),/Immediate availability preferred/); assert.match(r.text(),/Do legal work/); assert.doesNotMatch(r.text(),/secret/); assert.doesNotMatch(r.text(),/Draft preview/); const applyLinks=r.d.bodyEl.findByTag('a').filter(a=>/^mailto:hr@shorevest\.com/.test(a.href||'')); assert.strictEqual(applyLinks.length,1,'email application action is rendered'); assert.match(applyLinks[0].href,/Application%20-%20Legal%20Assistant%20-%20%5BFull%20Name%5D/); assert.strictEqual(r.d.bodyEl.findByTag('form').length,0,'no fake form');
r=render('zh-CN','legal-assistant',[role()]); assert.match(r.text(),/法务专员/); assert.match(r.text(),/法务主管/); assert.match(r.text(),/尽快到岗/); assert.match(r.text(),/通过邮件申请/); assert.match(r.d.bodyEl.findByTag('a').filter(a=>/^mailto:/.test(a.href||''))[0].href,/%E7%94%B3%E8%AF%B7%20-%20%E6%B3%95%E5%8A%A1%E4%B8%93%E5%91%98%20-%20%5B%E5%A7%93%E5%90%8D%5D/);
r=render('en','legal-assistant',[role('closed')]); assert.strictEqual(r.status,'closed'); assert.match(r.text(),/Applications are closed/); assert.strictEqual(r.d.bodyEl.findByTag('a').filter(a=>/^mailto:/.test(a.href||'')).length,0);
r=render('en','legal-assistant',[role('draft')]); assert.strictEqual(r.status,'draft'); assert.match(r.text(),/could not be found/); assert.doesNotMatch(r.text(),/Overview text|secret|Applications are not yet open/);
assert.doesNotThrow(()=>{ r=render('en','legal-assistant',[role('draft')], true); }); assert.strictEqual(r.status,'draft-preview'); assert.match(r.text(),/Legal Assistant/); assert.match(r.text(),/Draft preview/); assert.match(r.text(),/Applications are not yet open for this role/); assert.doesNotMatch(r.text(),/secret/); assert.strictEqual(r.d.bodyEl.children.item(0).getAttribute('data-recruitment-preview'),'true','preview notice is the first direct body node'); assert.strictEqual(r.d.bodyEl.children.item(1).className,'careers-section','role content follows the preview notice'); assert.strictEqual(invalidReplaceChildCount,0,'replaceChildren did not receive an HTMLCollection or other non-node'); assert.strictEqual(r.d.bodyEl.findByTag('form').length,0); assert.strictEqual(r.d.bodyEl.findByTag('button').length,0); assert.strictEqual(r.d.bodyEl.findByTag('input').length,0);
r=render('zh-CN','legal-assistant',[role('draft')], true); assert.match(r.text(),/法务专员/); assert.match(r.text(),/草稿预览/); assert.match(r.text(),/该职位暂未开放申请。/); assert.strictEqual(invalidReplaceChildCount,0);
r=render('en','unknown-role',[role()]); assert.strictEqual(r.status,'not-found');
r=render('en','bad id',[role()]); assert.strictEqual(r.status,'invalid-role');
const html=role(); html.title.en='<img src=x>Legal'; r=render('en','legal-assistant',[html]); assert.strictEqual(r.d.hero.findByTag('img').length,0); assert.strictEqual(innerHtmlWrites,0);
assert.doesNotMatch(renderer.encodeMailto('hr@shorevest.com','Application - Legal Assistant - [Full Name]','Full name:\nCV attached: Yes / No'),/[ \n\[\]]/);
assert.strictEqual(renderer.hasPreview({ location: { href: 'https://example.com/careers/legal-assistant.html?preview=1' } }), true);
assert.doesNotMatch(renderer.encodeMailto('hr@shorevest.com','Application - Legal Assistant - [Full Name]','Full name:\nCV attached: Yes / No'),/[ \n\[\]]/);
assert.strictEqual(renderer.hasPreview({ location: { href: 'https://example.com/careers/legal-assistant.html?preview=true' } }), false);
const fontLinks=[]; const fontClasses=[]; const fontDoc={documentElement:{lang:'zh-CN',classList:{add:v=>fontClasses.push(v)}},head:{appendChild:v=>fontLinks.push(v)},querySelector:()=>null,createElement:t=>new Element(t)}; assert.strictEqual(renderer.ensureChineseFont(fontDoc),true); assert.deepStrictEqual(fontClasses,['sv-cn-font-unified']); assert.strictEqual(fontLinks.length,1); assert.strictEqual(fontLinks[0].href,'/assets/css/chinese-font-uniform.css?v=20260722-cn-serif-unify'); assert.strictEqual(fontLinks[0].getAttribute('data-sv-cn-font'),'true');
console.log('recruitment role-detail renderer tests passed');
