const assert = require('assert');
const renderer = require('../assets/js/recruitment-role-detail');
let innerHtmlWrites = 0;
class Element { constructor(t){this.tagName=t.toUpperCase();this.children=[];this.attributes={};this.className='';this._textContent='';} appendChild(c){this.children.push(c);return c;} replaceChildren(...c){this.children=c;} set href(v){this.attributes.href=v;} get href(){return this.attributes.href;} set innerHTML(v){innerHtmlWrites++;this._textContent=String(v);} set textContent(v){this._textContent=String(v);this.children=[];} get textContent(){return this._textContent+this.children.map(c=>c.textContent).join('');} setAttribute(n,v){this.attributes[n]=String(v);} getAttribute(n){return this.attributes[n]||null;} findByTag(t,f=[]){if(this.tagName===t.toUpperCase())f.push(this);this.children.forEach(c=>c.findByTag(t,f));return f;} }
class Document { constructor(lang,id){this.documentElement={lang};this.hero=new Element('div');this.body_=new Element('body');if(id!==undefined)this.body_.attributes['data-recruitment-role-id']=id;this.bodyEl=new Element('section');this.langLink=new Element('a');this.langLink.className='sv-lang';this.langLink.attributes.href=id+'_cn.html';} get body(){return this.body_;} createElement(t){return new Element(t);} querySelector(s){if(s==='[data-role-detail="hero"]')return this.hero;if(s==='[data-role-detail="body"]')return this.bodyEl;return null;} querySelectorAll(s){return s.includes('sv-lang')?[this.langLink]:[];} }
function role(status='published'){return {id:'legal-assistant',slug:'legal-assistant',status,contentReviewRequired:false,contentReviewNote:'secret',title:{en:'Legal Assistant','zh-CN':'法务专员'},location:{en:'Guangzhou, China','zh-CN':'中国广东省广州市'},department:{en:'Legal Department','zh-CN':'法务部门'},reportingLine:{en:'Legal Supervisor','zh-CN':'法务主管'},employmentType:{en:'Full-time','zh-CN':'全职'},targetStartDate:{en:'Immediate availability preferred','zh-CN':'尽快到岗'},roleOverview:{en:'Overview text.','zh-CN':'概述。'},responsibilities:{en:['Do legal work'],'zh-CN':['法务工作']},requiredQualifications:{en:['Law degree'],'zh-CN':['法学学历']},preferredQualifications:{en:['Fund certificate preferred'],'zh-CN':['基金从业优先']},recruitmentStatus:{en:'Open until filled','zh-CN':'招到为止'},datePosted:'2026-07-20',dateUpdated:'2026-07-20',displayOrder:1};}
function render(lang,id,roles,preview=false){let d=new Document(lang,id);let status=renderer.renderRoleDetail(d,{schemaVersion:'1.0',roles},{roleId:id,preview});return {d,status,text:()=>d.hero.textContent+d.bodyEl.textContent};}
let r=render('en','legal-assistant',[role()]); assert.strictEqual(r.status,'published'); assert.match(r.text(),/Legal Assistant/); assert.match(r.text(),/Legal Supervisor/); assert.match(r.text(),/Immediate availability preferred/); assert.match(r.text(),/Do legal work/); assert.doesNotMatch(r.text(),/secret/); assert.doesNotMatch(r.text(),/Draft preview/); assert.strictEqual(r.d.bodyEl.findByTag('a').filter(a=>/apply/.test(a.href||'')).length,0,'no application action'); assert.strictEqual(r.d.bodyEl.findByTag('form').length,0,'no fake form');
r=render('zh-CN','legal-assistant',[role()]); assert.match(r.text(),/法务专员/); assert.match(r.text(),/法务主管/); assert.match(r.text(),/尽快到岗/);
r=render('en','legal-assistant',[role('closed')]); assert.strictEqual(r.status,'closed'); assert.match(r.text(),/Applications are closed/); assert.strictEqual(r.d.bodyEl.findByTag('a').filter(a=>/apply/.test(a.href||'')).length,0);
r=render('en','legal-assistant',[role('draft')]); assert.strictEqual(r.status,'draft'); assert.match(r.text(),/could not be found/); assert.doesNotMatch(r.text(),/Overview text|secret|Applications are not yet open/);
r=render('en','legal-assistant',[role('draft')], true); assert.strictEqual(r.status,'draft-preview'); assert.match(r.text(),/Legal Assistant/); assert.match(r.text(),/Draft preview/); assert.match(r.text(),/Applications are not yet open for this role/); assert.doesNotMatch(r.text(),/secret/); assert.strictEqual(r.d.bodyEl.findByTag('form').length,0); assert.strictEqual(r.d.bodyEl.findByTag('button').length,0); assert.strictEqual(r.d.bodyEl.findByTag('input').length,0);
r=render('zh-CN','legal-assistant',[role('draft')], true); assert.match(r.text(),/草稿预览/); assert.match(r.text(),/该职位暂未开放申请。/);
r=render('en','unknown-role',[role()]); assert.strictEqual(r.status,'not-found');
r=render('en','bad id',[role()]); assert.strictEqual(r.status,'invalid-role');
const html=role(); html.title.en='<img src=x>Legal'; r=render('en','legal-assistant',[html]); assert.strictEqual(r.d.hero.findByTag('img').length,0); assert.strictEqual(innerHtmlWrites,0);
assert.strictEqual(renderer.hasPreview({ location: { href: 'https://example.com/careers/legal-assistant.html?preview=1' } }), true);
assert.strictEqual(renderer.hasPreview({ location: { href: 'https://example.com/careers/legal-assistant.html?preview=true' } }), false);
console.log('recruitment role-detail renderer tests passed');
