const assert=require('assert');
const base=require('../assets/data/recruitment/roles.v1.json');
const {createMemoryAdapters,createMemoryBacking}=require('../api/recruitment/core/inMemoryAdapters');
const {initiateApplication,completeUpload,processScanResult}=require('../api/recruitment/core/flows');
const {CONTAINERS,APPLICATION_STATES:A,FILE_STATES:F,SCAN_RESULTS:S,ERROR_CODES:E}=require('../api/recruitment/core/constants');
function manifest(){const m=JSON.parse(JSON.stringify(base));m.roles=[Object.assign(m.roles.find(r=>r.id==='legal-assistant'),{status:'published',contentReviewRequired:false,application:{enabled:true,deadlineUtc:null,privacyNoticeVersion:'approved-v1',allowedSources:['website'],cv:{required:true,maxSizeBytes:100,allowedExtensions:['.pdf'],allowedMimeTypes:['application/pdf']}}})];return m;}
function req(p={}){return Object.assign({roleId:'legal-assistant',locale:'en',source:'website',clientSubmissionId:'550e8400-e29b-41d4-a716-446655440200',candidate:{fullName:'Candidate Name',email:'p@example.com',telephone:'',currentLocation:'',linkedinUrl:'',coverNote:''},privacyAccepted:true,privacyNoticeVersion:'approved-v1',submittedAtClientUtc:'2026-07-20T00:00:00Z',file:{originalName:'cv.pdf',declaredMimeType:'application/pdf',sizeBytes:9}},p);}
async function init(backing,id='550e8400-e29b-41d4-a716-446655440200',now=()=>new Date('2026-07-20T00:00:00Z')){const d=createMemoryAdapters({manifest:manifest(),backing,now});return initiateApplication(req({clientSubmissionId:id}),d);}
(async()=>{
let backing=createMemoryBacking(),d=createMemoryAdapters({manifest:manifest(),backing});
assert.strictEqual((await initiateApplication(req({candidate:{...req().candidate,email:'bad'}}),d)).errorCode,E.VALIDATION_FAILED);assert.strictEqual(backing.idempotency.size,0);assert.ok((await initiateApplication(req(),d)).success);
backing=createMemoryBacking();d=createMemoryAdapters({manifest:manifest(),backing});assert.strictEqual((await initiateApplication(req({privacyNoticeVersion:'old'}),d)).errorCode,E.PRIVACY_VERSION_INVALID);assert.strictEqual(backing.idempotency.size,0);assert.ok((await initiateApplication(req(),d)).success);
backing=createMemoryBacking();d=createMemoryAdapters({manifest:manifest(),backing});assert.strictEqual((await initiateApplication(req({file:{originalName:'cv.exe',declaredMimeType:'application/octet-stream',sizeBytes:9}}),d)).errorCode,E.FILE_TYPE_REJECTED);assert.strictEqual(backing.idempotency.size,0);assert.ok((await initiateApplication(req(),d)).success);
backing=createMemoryBacking();let first=await init(backing);assert.ok(first.success);let conflict=await initiateApplication(req({candidate:{...req().candidate,fullName:'Other Name'}}),createMemoryAdapters({manifest:manifest(),backing}));assert.strictEqual(conflict.errorCode,E.IDEMPOTENCY_CONFLICT);assert.strictEqual(backing.counters.applications,1);assert.strictEqual(backing.counters.files,1);
let nowMs=Date.parse('2026-07-20T00:00:00Z');backing=createMemoryBacking();first=await init(backing,'550e8400-e29b-41d4-a716-446655440201',()=>new Date(nowMs));nowMs+=11*60*1000;let second=await init(backing,'550e8400-e29b-41d4-a716-446655440201',()=>new Date(nowMs));assert.strictEqual(first.applicationReference,second.applicationReference);assert.strictEqual(first.fileReference,second.fileReference);assert.notStrictEqual(first.completionToken,second.completionToken);assert.strictEqual(second.credentialGeneration,2);assert.strictEqual(backing.counters.applications,1);assert.strictEqual(backing.counters.files,1);
d=createMemoryAdapters({manifest:manifest(),backing,now:()=>new Date(nowMs)});d.storage.put(CONTAINERS.quarantine,backing.files.get(first.fileReference).quarantineBlobPath,Buffer.from('%PDF-test'),'application/pdf');assert.strictEqual((await completeUpload({applicationReference:first.applicationReference,fileReference:first.fileReference,completionToken:first.completionToken},d)).errorCode,E.TOKEN_INVALID);assert.ok((await completeUpload({applicationReference:second.applicationReference,fileReference:second.fileReference,completionToken:second.completionToken},d)).success);let afterVerify=await init(backing,'550e8400-e29b-41d4-a716-446655440201',()=>new Date(nowMs+11*60*1000));assert.ok(afterVerify.alreadySubmitted);assert.ok(!afterVerify.upload);
let scanIds=['550e8400-e29b-41d4-a716-446655440202','550e8400-e29b-41d4-a716-446655440203','550e8400-e29b-41d4-a716-446655440204'];let scanI=0;for(const [result,fs,as,type] of [[S.Clean,F.Ready,A.Ready,'DocumentsReady'],[S.Malicious,F.Malicious,A.Blocked,'MaliciousFileDetected'],[S.ScanFailed,F.ManualReview,A.ManualReview,'ManualReviewRequired']]){backing=createMemoryBacking();let started=await init(backing,scanIds[scanI++]);let ad=createMemoryAdapters({manifest:manifest(),backing});ad.storage.put(CONTAINERS.quarantine,backing.files.get(started.fileReference).quarantineBlobPath,Buffer.from('%PDF-test'),'application/pdf');await completeUpload({applicationReference:started.applicationReference,fileReference:started.fileReference,completionToken:started.completionToken},ad);let ev={eventId:`evt-${result}`,fileReference:started.fileReference,blobPath:backing.files.get(started.fileReference).quarantineBlobPath,result,scannedAtUtc:'2026-07-20T00:05:00Z'};assert.strictEqual((await processScanResult(ev,createMemoryAdapters({manifest:manifest(),backing,failures:{scanEventsComplete:1}}))).errorCode,E.INFRASTRUCTURE_RETRYABLE);assert.strictEqual(backing.files.get(started.fileReference).technicalStatus,fs);assert.strictEqual(backing.apps.get(started.applicationReference).technicalStatus,as);assert.ok((await processScanResult(ev,createMemoryAdapters({manifest:manifest(),backing}))).success);assert.strictEqual(backing.outbox.filter(e=>e.type===type).length,1);}
backing=createMemoryBacking();backing.completionClaims.set('complete:a:f',{key:'complete:a:f',state:'PermanentFailure',reason:E.TOKEN_INVALID,leaseExpiresAtUtc:'2026-07-20T00:05:00Z'});assert.strictEqual((await completeUpload({applicationReference:'a',fileReference:'f',completionToken:'x.y'},createMemoryAdapters({manifest:manifest(),backing}))).errorCode,E.TOKEN_INVALID);
console.log('phase 2a.3 recruitment idempotency and reconciliation tests passed');
})();
