const assert = require('assert');
const fs = require('fs');
const path = require('path');
const renderer = require('../assets/js/recruitment-role-list');
class Element { constructor(t){this.tagName=t.toUpperCase();this.children=[];this.className='';this.attributes={};this._textContent='';} appendChild(c){this.children.push(c);return c;} replaceChildren(...c){this.children=c;} set href(v){this.attributes.href=v;} get href(){return this.attributes.href;} set textContent(v){this._textContent=String(v);this.children=[];} get textContent(){return this._textContent+this.children.map(c=>c.textContent).join('');} querySelectorAllByClass(c,f=[]){if(this.className===c)f.push(this);this.children.forEach(x=>x.querySelectorAllByClass(c,f));return f;} findByTag(t,f=[]){if(this.tagName===t.toUpperCase())f.push(this);this.children.forEach(x=>x.findByTag(t,f));return f;} }
class Document { constructor(lang, empty='We do not currently have any open roles.'){this.documentElement={lang};this.container=new Element('div');this.container.attributes['data-role-list']='open-roles';let p=new Element('p');p.className='careers-role-empty';p.textContent=empty;this.container.appendChild(p);} createElement(t){return new Element(t);} querySelector(s){return s==='[data-role-list="open-roles"]'?this.container:null;} }
const checkedInManifest = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'assets/data/recruitment/roles.v1.json'), 'utf8'));
function rows(d){return d.container.querySelectorAllByClass('careers-role-row');} function links(d){return d.container.findByTag('a');}
function role(id,status='published'){return {id,slug:id,status,contentReviewRequired:false,contentReviewNote:'',title:{en:`Title ${id}`,'zh-CN':`职位 ${id}`},location:{en:'Guangzhou, China','zh-CN':'中国广东省广州市'},department:{en:'Legal Department','zh-CN':'法务部门'},reportingLine:{en:'Supervisor','zh-CN':'主管'},employmentType:{en:'Full-time','zh-CN':'全职'},targetStartDate:{en:'Rolling','zh-CN':'长期'},roleOverview:{en:'Overview','zh-CN':'概述'},responsibilities:{en:['R'],'zh-CN':['职责']},requiredQualifications:{en:['Q'],'zh-CN':['要求']},preferredQualifications:{en:['P'],'zh-CN':['优先']},recruitmentStatus:{en:'Open until filled','zh-CN':'招到为止'},datePosted:'2026-07-20',dateUpdated:'2026-07-20',displayOrder:1};}
function manifest(roles){return {schemaVersion:'1.0',generatedAtUtc:'2026-07-20T00:00:00Z',roles};}
let d=new Document('en'); assert.strictEqual(renderer.renderRolesFromManifest(d, checkedInManifest, {featureEnabled:true}),0,'draft checked-in roles do not render'); assert.match(d.container.textContent,/currently have any open roles/i);
d=new Document('en'); assert.strictEqual(renderer.renderRolesFromManifest(d, manifest([role('legal-assistant')]), {featureEnabled:false}),0,'feature flag disabled keeps fallback');
d=new Document('en'); assert.strictEqual(renderer.renderRolesFromManifest(d, manifest([role('legal-assistant')]), {featureEnabled:true}),1,'published role renders when enabled'); assert.match(d.container.textContent,/Title legal-assistant/); assert.deepStrictEqual(links(d).map(a=>a.href),['careers/legal-assistant.html']);
d=new Document('zh-CN','我们目前暂无开放职位。'); assert.strictEqual(renderer.renderRolesFromManifest(d, manifest([role('legal-assistant')]), {featureEnabled:true}),1,'Chinese published role renders'); assert.match(d.container.textContent,/职位 legal-assistant/); assert.match(d.container.textContent,/全职/); assert.deepStrictEqual(links(d).map(a=>a.href),['careers/legal-assistant_cn.html']);
d=new Document('en'); assert.strictEqual(renderer.renderRolesFromManifest(d, manifest([role('legal-assistant','closed')]), {featureEnabled:true}),0,'closed role does not render on careers list');
assert.strictEqual(renderer.isSafeDetailPath('careers/legal-assistant.html','en'), true); assert.strictEqual(renderer.isSafeDetailPath('mailto:test@example.com','en'), false);
console.log('recruitment role-list renderer tests passed');
