'use strict';
const crypto=require('crypto');
const {ERROR_CODES}=require('./constants');
const {ext,hasPathTraversal}=require('./fileTypes');
const LIMITS={fullName:200,email:254,telephone:50,currentLocation:200,linkedinUrl:300,coverNote:4000,originalName:255};
function safeEqual(a,b){const x=Buffer.from(String(a||''));const y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y);}
function normalizeEmail(v){if(typeof v!=='string')return '';const t=v.trim();const at=t.lastIndexOf('@');return at<0?t:t.slice(0,at)+'@'+t.slice(at+1).toLowerCase();}
function validEmail(v){return typeof v==='string'&&v.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
function role(manifest,roleId,locale,privacyVersion,now){if(typeof roleId!=='string'||!/^[a-z0-9][a-z0-9-]{2,80}$/.test(roleId))return {ok:false,errorCode:ERROR_CODES.ROLE_NOT_FOUND};const r=manifest&&Array.isArray(manifest.roles)&&manifest.roles.find(x=>x.id===roleId);if(!r)return {ok:false,errorCode:ERROR_CODES.ROLE_NOT_FOUND};if(r.status!=='published'||r.application?.enabled!==true||r.contentReviewRequired===true)return {ok:false,errorCode:ERROR_CODES.ROLE_NOT_OPEN};if(!r.title||!Object.prototype.hasOwnProperty.call(r.title,locale))return {ok:false,errorCode:ERROR_CODES.VALIDATION_FAILED};const pv=r.application.privacyNoticeVersion;if(typeof pv!=='string'||pv.trim()===''||!safeEqual(pv,privacyVersion))return {ok:false,errorCode:ERROR_CODES.PRIVACY_VERSION_INVALID};if(r.application.deadlineUtc&&Date.parse(r.application.deadlineUtc)<(now?now.getTime():Date.now()))return {ok:false,errorCode:ERROR_CODES.APPLICATION_DEADLINE_PASSED};return {ok:true,role:r};}
function candidate(c,privacyAccepted){const bad=[];c=c||{};if(typeof c.fullName!=='string'||!c.fullName.trim())bad.push('fullName');if(!validEmail(normalizeEmail(c.email||'')))bad.push('email');for(const [k,n] of Object.entries(LIMITS)){if(k==='originalName')continue;if(typeof c[k]==='string'&&c[k].length>n)bad.push(k);}if(c.linkedinUrl&&(!/^https:\/\//i.test(c.linkedinUrl.trim())||!/linkedin\./i.test(c.linkedinUrl)))bad.push('linkedinUrl');if(privacyAccepted!==true)bad.push('privacyAccepted');return bad.length?{ok:false,errorCode:ERROR_CODES.VALIDATION_FAILED,fields:[...new Set(bad)]}:{ok:true,candidate:{fullName:c.fullName.trim(),email:normalizeEmail(c.email),telephone:(c.telephone||'').trim(),currentLocation:(c.currentLocation||'').trim(),linkedinUrl:(c.linkedinUrl||'').trim(),coverNote:(c.coverNote||'').trim()}};}
function fileMeta(f,cv){if(!f)return {ok:false,errorCode:ERROR_CODES.FILE_MISSING};if(typeof f.originalName!=='string'||!f.originalName.trim()||f.originalName.length>LIMITS.originalName||hasPathTraversal(f.originalName))return {ok:false,errorCode:ERROR_CODES.VALIDATION_FAILED};const e=ext(f.originalName);if(cv.allowedExtensions.indexOf(e)===-1)return {ok:false,errorCode:ERROR_CODES.FILE_TYPE_REJECTED};if(cv.allowedMimeTypes.indexOf(f.declaredMimeType)===-1)return {ok:false,errorCode:ERROR_CODES.FILE_TYPE_REJECTED};if((e==='.pdf'&&f.declaredMimeType!=='application/pdf')||(e==='.docx'&&f.declaredMimeType!=='application/vnd.openxmlformats-officedocument.wordprocessingml.document'))return {ok:false,errorCode:ERROR_CODES.FILE_TYPE_REJECTED};if(!Number.isInteger(f.sizeBytes)||f.sizeBytes<1||f.sizeBytes>cv.maxSizeBytes)return {ok:false,errorCode:ERROR_CODES.FILE_TOO_LARGE};return {ok:true,extension:e.slice(1)};}
module.exports={LIMITS,safeEqual,normalizeEmail,validEmail,role,candidate,fileMeta};
